### ISSUE TITLE
Not working in iOS 13+

### ISSUE THREAD

**Issue by steveGates890** [timshim/MightyTabBar#1]
Hi, dev I'm currently using MightyTabBar as per my requirements, it's working fine in below iOS 13 but in devices iOS 13 and above tabBar not working properly. Expanding functionality is not working in iOS 13 as same as other iOS version

**Comment by timshim** [comment]
Oh Apple, why do you have to break layout in iOS 13 ...
I've fixed the issue but it seems more like a workaround to some bugginess in iOS 13.
